### ISSUE TITLE
Lack of documentation on how to configure and write tests

### ISSUE THREAD

**Issue by your** [ministryofjustice/laa-cwa-feature-tests#111]
#110 introduced a "CWA Configuration loader", currently implementing most of the pricing rules and formulas, but for a limited number of categories of law. This opens up the path to isolating more logic from CWA.

So far, this has been tentatively used to remove excess data input in feature tests and in favour of a more natural-language oriented testing style.

Despite the noble attempt, without proper documentation and guidance on how to continue and complete the refactoring work, this will soon turn into another pile of tech debt.

**Comment by vimalsuresh** [comment]
Closing this as we have added relevant information to the wiki already. Any more details from now on will be added as part of PR approvals.
