### ISSUE TITLE
MT combinations which are only valid for ECF funding might need to be defined in the lib files

### ISSUE THREAD

**Issue by solomonahmed** [ministryofjustice/laa-cwa-feature-tests#115]
Some MT combinations are only valid when used with an ECF ref.  For example, from the guidance:-

WREV Revision/supersession /
Where the client requests review or supersession of a decision. / 
To be used in ECF cases only

The above is a MT2 code in Welfare Benefits.  If we are randomly using combinations for the pricing tests (which is a great idea!) we will need to add in some configuration (I'm guessing to the lib files?) to ensure we perhaps complete the ECF ref field for those MT2 codes which require it.  The pricing tests are focused on pricing so whether fields are completed or not to support getting the MT combination pass validation is irrelevant for them as the important point is does the valid combination price correctly.  But, we might want to add something in the lib files to codify these ECF related MTs?

**Comment by your** [comment]
@solomonahmed we could start with defining a list of MT2 codes that can be used in ECF cases only:

```ruby
module SubmissionConfig
  module CategoriesOfLaw
    class WelfareBenefits < Base
      ...
      define_ecf_only_matter_type2_codes %i[WREV]
      ...
    end
  end
end
```

```ruby
module SubmissionConfig
  module Models
    class MatterType < ClaimCode
      ...
      def ecf_only?
        @matter_type2.ecf_only
      end
      ...
    end
  end
end
```

```ruby
module SubmissionConfig
  module Models
    class MatterType2 < ClaimCode
      attr_accessor :ecf_only
      ...
      def initialize
        ...
        @ecf_only = false
      end
    end
  end
end
```

```ruby
module SubmissionConfig
  class ConfigBuilder
    attr_reader *%i[
      ...
      ecf_only_matter_type2_codes,
      ...
    ]

    def initialize(
      ...
      ecf_only_matter_type2_codes:,
      ...)
      build_ecf_only_matter_type2_codes(ecf_only_matter_type2_codes),
      ...
    )

    build_ecf_only_matter_type2_codes(ecf_only_matter_type2_codes)
      ecf_only_matter_type2_codes.each do |ecf_only_matter_type2_code|
        @matter_type2_codes.find do |matter_type2_code|
          matter_type2_code.name == ecf_only_matter_type2_code
        end.tap do |matter_type2_code|
          matter_type2_code.ecf_only = true
        end
      end
    end
  end
end
```

Then – one option could be to start generating Outcomes from any MT and for any valueset / category of law that we have defined. The builder method on the `MatterType` class could then rely on the  `ecf_only?` above to decide whether an ECF field needs to be set or not.

**Comment by solomonahmed** [comment]
Sounds good.   You'll have to run through this with me as not entirely clear on how the builder method would work.

**Comment by vimalsuresh** [comment]
won't do this as we want to disallow randomly assigned MT1:MT2 to the tests.
