### ISSUE TITLE
refactor step definition

### ISSUE THREAD

**Issue by vimalsuresh** [ministryofjustice/laa-cwa-feature-tests#202]
Some tests require , no schedule reference to be entered as part of the outcome validation as the start dates are earlier than 2012/13. This required a hack in the existing code to exclude filling in schedule ref in those tests using exclusion's to values in hash. 

Similarly, there was an additional code introduced to exclude the case start date from the outcome screen and test the future date for the case start date. 

These have made the step definition unmanageable. This code block needs to be refactored

  if !outcome.has_key?("schedule_ref")
            outcome['schedule_ref'] = CWAProvider.submission.schedule_ref
    end
    if !outcome.has_key?("case_start_date") && !(area_of_law == "Crime Lower")
      outcome['case_start_date'] = (Date.today + 1).strftime("%d-%b-%Y") 
    end

The line in question is 
https://github.com/ministryofjustice/laa-cwa-feature-tests/blob/8afcc15791a8e596ad3fdb3dddb809208b2e7d90/features/step_definitions/cwa_outcome_steps.rb#L66-L71

**Comment by vimalsuresh** [comment]
Ticket created https://dsdmoj.atlassian.net/browse/TA-2635

**Comment by idlecursor** [comment]
Hi
