### ISSUE TITLE
Failing/flaky scenarios

### ISSUE THREAD

**Issue by your** [ministryofjustice/laa-cwa-feature-tests#49]
The following seems to fail quite consistently:

```
Failing Scenarios:
cucumber features/add_outcome.feature:10 # Scenario: Add an outcome with AP00000 before 1st July case start date
cucumber features/procurement_area_and_access_point_validation.feature:11 # Scenario Outline: Add an outcome sucessfully, Examples (#1)
cucumber features/procurement_area_and_access_point_validation.feature:15 # Scenario Outline: Add an outcome sucessfully, Examples (#5)

29 scenarios (3 failed, 1 undefined, 25 passed)
108 steps (1 failed, 1 undefined, 106 passed)
11m21.620s
```

According to @davidkelliott this is always been the case, but it would be good to investigate why and fix or remove them if unneeded (if they fail, they give no confidence). 

In all cases the problem seems to be the `delete_all_outcomes` after hook:

```
      Unable to find link "Select All" (Capybara::ElementNotFound)
      ./features/pages/outcome_page.rb:96:in `delete_all_outcomes'
      ./features/support/hooks.rb:5:in `After'
```

**Comment by sldblog** [comment]
🥇 for raising

**Comment by sldblog** [comment]
💭 It may be worth to rework the scenario names too. Unfortunately, I don't know what business value/process we mean by "Add an outcome with AP00000 before 1st July case start date".

**Comment by your** [comment]
> It may be worth to rework the scenario names too

Agreed on that 👍. Think it's just _one_ case (of the many probably) where the start date would basically let succeed or fail the outcome addition, and that's what these scenarios should be, a valid and an invalid submission.
