### ISSUE TITLE
Ruby version for the project

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/laa-cwa-feature-tests#5]
How could we set out which Ruby version is expected to be used with this project?

Should/could we have a `.ruby-version` file?

**Comment by your** [comment]
According to https://www.ruby-lang.org/en/downloads/ as of today we should be using either `2.5.5` or `2.6.3` as these are the only stable releases. I've recently worked at some ruby upgrades elsewhere and I would strongly advice against the `2.6.x` trunk at the moment (possible reason why we have 2 stable releases from two different trunks – meh), so we should go for `2.5.5`.

I'm actually introducing a `.ruby-version` file in #44, but with `2.3.7` (for no real reason). Happy to bump it to `2.5.5` once that gets merged.
