### ISSUE TITLE
Revisit the way we delete outcomes for scenarios tagged with @delete_outcome_after

### ISSUE THREAD

**Issue by your** [ministryofjustice/laa-cwa-feature-tests#59]
Currently it's a bit fiddle and probably not even reliable.

Also, can't we run it before running scenarios? Consider speed and impact of the change.

**Comment by your** [comment]
Related: #49

**Comment by solomonahmed** [comment]
Thinking about this maybe we should implement a step to clean the db via DELETE statements on XXLSC_AM_LINES?  If running these tests on a Mac this inevitably means you'll need bastion access to the relevant env.  This could be set via a env var - BASTION_ACCESS=true?  As long as we can identify the lines the tests have added in each case, i.e. sub lines, then deleting them via BASTION access would be quick.  With the direct access to CWA in place this opens up other testing opportunities as well.

**Comment by vimalsuresh** [comment]
Ticket is raised to look at the above issue. https://dsdmoj.atlassian.net/browse/TA-2624
