### ISSUE TITLE
Extract valuesets/errors to different YAML files

### ISSUE THREAD

**Issue by your** [ministryofjustice/laa-cwa-feature-tests#77]
Currently the `cwa_env.yml` file is getting crowded. The `CWAProvider` should be refactored to reflect a more complex representation of static configuration from CWA (not always dependant on the environments).

**Comment by solomonahmed** [comment]
I did wonder whether we should pull out things like the errors in realtime from the db.  Setting up CWA so we can use REST involves installed APEX which might be problematic (or might not!).  We already have APEX installed elsewhere (running PIMS etc...).  Maybe we can re-purpose APEX there and create some service we can use?  Just thinking as soon as we embed the lists of the category fee schemes and the errors we are essentially duplicating information in the database.

**Comment by solomonahmed** [comment]
The way that the field codes are included in the file mapping to screens displayed for a particular cat of law also needs to be refactored and moved out.  One approach could be to simplify it all by starting with a default set of fields applicable to all screens and then extend this for each screen which has particular requirements.

e.g. 

class DefaultScreen
  clientFirstName
  clientSurname
  ...etc...

class WelfareBenefits < DefaultScreen
  TypeOfAdvice

**Comment by solomonahmed** [comment]
These classes can be built programmatically from the db using a script.

**Comment by solomonahmed** [comment]
We also have errors in the .env file.  We could either re-consider this approach or move these out to another file.  Again, easy enough to do via a script.

**Comment by solomonahmed** [comment]
Best place for the screen codes seems to be the \lib folder as the screens are configured by cat of law (at least for LEGAL HELP).

**Comment by solomonahmed** [comment]
I guess in base.rb?
