### ISSUE TITLE
Update README to describe git-crypt setup for maintaners

### ISSUE THREAD

**Issue by your** [ministryofjustice/laa-cwa-feature-tests#84]
It's actually missing context and relies on personal knowledge, or internal to the team.
Could be an opportunity to also expand the description of the repository.

**Comment by solomonahmed** [comment]
We should perhaps progress this via a ticket.  Without git-crypt unlock working you basically can't run any tests (I believe).  To get git-crypt working seems to require other things as well (gpg).  To install gpg is usually done via homebrew.  Which requires homebrew....etc...etc.. 

Maybe we can get a sprint ticket for this (or agree to do in L&D soon?).
